from model.low_memory_near_linear_time_randomized_filtering import delete as low_mem_delete
from model.randomized_filtering import delete as rf_delete
from model.near_linear_time_randomized_filtering import delete as linear_delete
